workflows:
  ios-project-debug:
    name: iOS Debug with Quality Checks
    environment:
      xcode: latest
      vars:
        XCODE_SCHEME: "GameCenter" # Replace with your actual scheme name
    scripts:
      - name: Run tests with code coverage
        script: |
          xcodebuild \
            -workspace "GameCenter.xcworkspace" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0' \
            clean build test \
            -enableCodeCoverage YES \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
      - name: Generate code coverage report
        script: |
          mkdir -p code_coverage
          xcrun xccov view --report --json \
            $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult \
            > code_coverage/coverage.json
      - name: Check code style
        script: |
          # Ensure SwiftLintPlugin is used correctly
          echo "SwiftLint is integrated via SwiftLintPlugin in SPM."
          echo "To run SwiftLint, use the following command during development:"
          echo "swift run swiftlint --path ./"
          # Optional: Include SwiftLint checks in CI if required
          swift run swiftlint --strict
      - name: Check vulnerabilities
        script: |
          brew install trivy || echo "Trivy already installed"
          trivy fs . --exit-code 1 --severity CRITICAL
      - name: Build debug app
        script: |
          xcodebuild \
            -workspace "GameCenter.xcworkspace" \
            -scheme "$XCODE_SCHEME" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - code_coverage/coverage.json
    publishing:
      email:
        recipients:
          - stevenliee1206@gmail.com
