workflows:
  ios-project-debug:
    name: iOS Debug with Quality Checks
    environment:
      xcode: latest
      vars:
        XCODE_SCHEME: "GameCenter" # Replace with your actual scheme name
    scripts:
      - name: Resolve SPM dependencies
        script: |
          xcodebuild -resolvePackageDependencies
      - name: Run tests with code coverage
        script: |
          xcodebuild \
          -project "GameCenter.xcodeproj" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0' \
          clean build test \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
      - name: Generate code coverage report
        script: |
          mkdir -p code_coverage
          xcrun xccov view --report --json \
            $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult \
            > code_coverage/coverage.json
      - name: Check code style
        script: |
          SWIFT_PACKAGE_DIR="${BUILD_DIR%Build/*}SourcePackages/artifacts"
          SWIFTLINT_CMD=$(find "$SWIFT_PACKAGE_DIR" -name swiftlint -type f | head -n 1)
      
          if [ -n "$SWIFTLINT_CMD" ] && [ -x "$SWIFTLINT_CMD" ]; then
              echo "Running SwiftLint from $SWIFTLINT_CMD..."
              "$SWIFTLINT_CMD" --path ./ || {
                  echo "warning: SwiftLint found issues or exited with a warning."
                  exit 0 # Exit gracefully even if linting has warnings
              }
          else
              echo "error: SwiftLint command not found. Ensure SPM SwiftLintPlugin is correctly configured."
              exit 1
          fi
      - name: Check vulnerabilities
        script: |
          brew install trivy || echo "Trivy already installed"
          trivy fs . --exit-code 1 --severity CRITICAL
      - name: Build debug app
        script: |
          xcodebuild \
            -workspace "GameCenter.xcworkspace" \
            -scheme "$XCODE_SCHEME" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - code_coverage/coverage.json
    publishing:
      email:
        recipients:
          - stevenliee1206@gmail.com
